sudo: required
language: generic
services:
  - docker

script:
  - make tests coverage
  - make build

deploy:
  # Production
  - provider: script
    script: make upload-coverage deploy-live
    skip_cleanup: true
    on:
      branch: master
      tags: true
  # Development
  - provider: script
    script: make upload-coverage deploy-develop
    skip_cleanup: true
    on:
      branch: develop
