sudo: required
language: generic
services:
  - docker

script:
  - make tests coverage
  - make build

deploy:
  # Production
  - provider: script
    # upload-coverage
    script: make deploy-live
    skip_cleanup: true
    on:
      branch: master
      tags: true
  # Development
  - provider: script
    # upload-coverage
    script: make deploy-develop
    skip_cleanup: true
    on:
      branch: develop
